spring:
  application:
    name: order-service

# Configuration for the inventory service
inventory:
  service:
    url: http://localhost:8081/inventory/
  circuit-breaker:
    name: inventory-circuit-breaker
    sliding-window-size: 10
    failure-rate-threshold: 30
    slow-call-rate-threshold: 50
    slow-call-duration-threshold-milis: 2000
    wait-duration-in-open-state-milis: 5000
    permitted-number-of-calls-in-half-open-state: 3
    timeout-duration-milis: 10000

# Configuration for Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Configuration for Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  health.circuitbreakers.enabled: true

# logging configuration
logging:
  level:
    io:
      github:
        resilience4j:
          circuitbreaker: DEBUG