spring:
  application:
    name: order-service

# Configuration for the inventory service
inventory:
  service:
    url: http://localhost:8081/inventory/

# Configuration for resilience4j circuit breaker
spring-cloud-resilience4j:
  circuitbreaker:
    instances:
      inventory-circuit-breaker:
        name: inventory-circuit-breaker
        #registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 60000  # 1 min
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 2000 # 2 seconds

# Configuration for Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Configuration for Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
  health.circuitbreakers.enabled: true

# logging configuration
logging:
  level:
    io:
      github:
        resilience4j:
          circuitbreaker: DEBUG